<?php

namespace VirtualLibraries;

require_once 'config.php';


/**
 * Test Sql statements generated by BookFilter 
 * The sql statements are logged, no unit tests !
 * @author Jürgen
 *
 */
class bookFilterTest
{
    static public function test($vlib)
    {
        $filter = new BookFilter();
        if ($filter->prepareFilter($vlib))
        {
            $sql = $filter->getSql(array( "id", "title", "authors", "genre", "pubdate" ));

            $log = \Logger::getLogger(__CLASS__);
            $log->info("Printing a sql query for Calibre books table:\n$vlib\n$sql");
        }
    }
}

bookFilterTest::test('authors:"Balzac"');                               // a string comparison

bookFilterTest::test('pubdate:>2008-01-01');                            // a value comparison (pubdate earlier than 2008)

bookFilterTest::test('#genre:false');                                   // a bool comparison (no genre defined)

bookFilterTest::test('pubdate:true');                                   // a bool comparison (no pubdate defined)

bookFilterTest::test('search:"Verstecke Calibre und Literatur"');       // a bool comparison (no pubdate defined)

bookFilterTest::test('pubdate:=2008');
